### ISSUE TITLE
usb connection

### ISSUE THREAD

**Issue by Jorge1976** [fieldOfView/Cura-SerialConnection#1]
hello, i want to apply this mockup on cura 2.5, but i am not a programmer, can you help me? please

**Comment by fieldOfView** [comment]
Do you know what a mockup is? The code in this repository is not functional. It is a (mostly visual) proposal of how a future iteration of Cura could handle USB connections.

I am working to actually implement this proposal (see https://github.com/Ultimaker/Cura/pull/1688), but progress is somewhat slow because I have also been working on other things.
